### ISSUE TITLE
Better feedback of HTML syntax errors

### ISSUE THREAD

**Issue by marcospont** [ericclemmons/grunt-angular-templates#141]
ngTemplate task stops when a syntax error is found in any HTML file.

Even using --verbose in grunt, the syntax errors are not visible.

**Comment by underscorebrody** [comment]
@marcospont In my testing just now i created a syntax error in an HTML file and got feedback from the grunt task saying there was a `Parse Error` with a reference to the line. Can you provide an example where syntax errors are being swallowed?

**Comment by eduardoinnorway** [comment]
This is still an issue, and there is nothing to provide because we dont know why it gets stuck, refer to this issue:
https://github.com/ericclemmons/grunt-angular-templates/issues/112

**Comment by underscorebrody** [comment]
I was able to get my grunt task to hang, but unfortunately the issue lies in `html-minifier` so we don't control it. With `--verbose` on you should now be able to see which template it was processing when it started hanging. I would also recommend trying https://github.com/htmllint/grunt-htmllint if you're running into this problem as that should hopefully help you catch it ahead of time.
